name: Build Docker Image for K8s CronJob

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build Docker Image only
    runs-on: self-hosted

    steps:
      # 1. 소스 코드 가져오기
      - name: 1. Checkout source code
        uses: actions/checkout@v4

      # 2. Docker 이미지 빌드
      - name: 2. Build Docker Image
        run: docker build -t kis-master-updater:latest .

      # 3. 디스크 공간 확보를 위한 정리
      - name: 3. Prune Old Images
        continue-on-error: true
        run: docker image prune -f